export const pokemonColor: Record<string, string> = {
    // Black Pokémon
    snorlax: "black",
    murkrow: "black",
    unown: "black",
    sneasel: "black",
    umbreon: "black",
    houndour: "black",
    houndoom: "black",
    mawile: "black",
    spoink: "black",
    seviper: "black",
    shuppet: "black",
    duskull: "black",
    claydol: "black",
    banette: "black",
    dusclops: "black",
    chatot: "black",
    munchlax: "black",
    honchkrow: "black",
    giratina: "black",
    darkrai: "black",
    blitzle: "black",
    weavile: "black",
    dusknoir: "black",
    zebstrika: "black",
    sigilyph: "black",
    yamask: "black",
    lampent: "black",
    zekrom: "black",
    scatterbug: "black",
    spewpa: "black",
    pikipek: "black",
    salandit: "black",
    trumbeak: "black",
    toucannon: "black",
    salazzle: "black",
    pyukumuku: "black",
    xurkitree: "black",
    guzzlord: "black",
    necrozma: "black",
    rolycoly: "black",
    carkol: "black",
    coalossal: "black",
    spectrier: "black",
    chandelure: "black",

    // Blue Pokémon
    squirtle: "blue",
    poliwhirl: "blue",
    "nidoran-f": "blue",
    oddish: "blue",
    poliwag: "blue",
    tentacool: "blue",
    wartortle: "blue",
    blastoise: "blue",
    nidorina: "blue",
    nidoqueen: "blue",
    gloom: "blue",
    golduck: "blue",
    poliwhril: "blue",
    poliwrath: "blue",
    tentacruel: "blue",
    tangela: "blue",
    horsea: "blue",
    lapras: "blue",
    omanyte: "blue",
    articuno: "blue",
    dratini: "blue",
    seadra: "blue",
    gyarados: "blue",
    vaporeon: "blue",
    omastar: "blue",
    dragonair: "blue",
    totodile: "blue",
    chinchou: "blue",
    wooper: "blue",
    heracross: "blue",
    croconaw: "blue",
    feraligatr: "blue",
    lanturn: "blue",
    marill: "blue",
    azumarill: "blue",
    jumpluff: "blue",
    quagsire: "blue",
    wobbuffet: "blue",
    phanpy: "blue",
    suicune: "blue",
    mudkip: "blue",
    taillow: "blue",
    surskit: "blue",
    azurill: "blue",
    kingdra: "blue",
    marshtomp: "blue",
    swampert: "blue",
    swellow: "blue",
    masquerain: "blue",
    loudred: "blue",
    exploud: "blue",
    meditite: "blue",
    wailmer: "blue",
    swablu: "blue",
    wynaut: "blue",
    spheal: "blue",
    clamperl: "blue",
    bagon: "blue",
    beldum: "blue",
    sharpedo: "blue",
    wailord: "blue",
    altaria: "blue",
    whiscash: "blue",
    chimecho: "blue",
    sealeo: "blue",
    walrein: "blue",
    huntail: "blue",
    salamence: "blue",
    metang: "blue",
    regice: "blue",
    latios: "blue",
    kyogre: "blue",
    piplup: "blue",
    shinx: "blue",
    cranidos: "blue",
    gible: "blue",
    riolu: "blue",
    croagunk: "blue",
    prinplup: "blue",
    empoleon: "blue",
    luxio: "blue",
    luxray: "blue",
    rampardos: "blue",
    gabite: "blue",
    garchomp: "blue",
    lucario: "blue",
    finneon: "blue",
    mantyke: "blue",
    azelf: "blue",
    phione: "blue",
    manaphy: "blue",
    oshawott: "blue",
    panpour: "blue",
    roggenrola: "blue",
    woobat: "blue",
    lumineon: "blue",
    tangrowth: "blue",
    glaceon: "blue",
    dewott: "blue",
    samurott: "blue",
    simipour: "blue",
    boldore: "blue",
    gigalith: "blue",
    swoobat: "blue",
    tympole: "blue",
    sawk: "blue",
    tirtouga: "blue",
    ducklett: "blue",
    karrablast: "blue",
    elgyem: "blue",
    palpitoad: "blue",
    seismitoad: "blue",
    carracosta: "blue",
    eelektrik: "blue",
    eelektross: "blue",
    cryogonal: "blue",
    deino: "blue",
    cobalion: "blue",
    thundurus: "blue",
    froakie: "blue",
    inkay: "blue",
    zweilous: "blue",
    hydreigon: "blue",
    frogadier: "blue",
    greninja: "blue",
    meowstic: "blue",
    clauncher: "blue",
    amaura: "blue",
    bergmite: "blue",
    xerneas: "blue",
    popplio: "blue",
    wishiwashi: "blue",
    mareanie: "blue",
    clawitzer: "blue",
    aurorus: "blue",
    avalugg: "blue",
    primarina: "blue",
    vikavolt: "blue",
    toxapex: "blue",
    komala: "blue",
    cosmog: "blue",
    sobble: "blue",
    rookidee: "blue",
    blipbug: "blue",
    cosmoem: "blue",
    drizzile: "blue",
    inteleon: "blue",
    corvisquire: "blue",
    cramorant: "blue",
    eiscue: "blue",
    arctozolt: "blue",
    arctovish: "blue",
    zacian: "blue",
    metagross: "blue",
    toxicroak: "blue",
    malamar: "blue",
    brionne: "blue",
    grapploct: "blue",

    // Brown Pokémon
    weedle: "brown",
    pidgey: "brown",
    spearow: "brown",
    vulpix: "brown",
    diglett: "brown",
    mankey: "brown",
    growlithe: "brown",
    abra: "brown",
    geodude: "brown",
    pidgeotto: "brown",
    pidgeot: "brown",
    raticate: "brown",
    fearow: "brown",
    dugtrio: "brown",
    primeape: "brown",
    arcanine: "brown",
    kadabra: "brown",
    alakazam: "brown",
    graveler: "brown",
    farfetchd: "brown",
    doduo: "brown",
    cubone: "brown",
    kangaskhan: "brown",
    staryu: "brown",
    pinsir: "brown",
    tauros: "brown",
    eevee: "brown",
    kabuto: "brown",
    dodrio: "brown",
    marowak: "brown",
    hitmonlee: "brown",
    hitmonchan: "brown",
    kabutops: "brown",
    dragonite: "brown",
    sentret: "brown",
    hoothoot: "brown",
    teddiursa: "brown",
    swinub: "brown",
    furret: "brown",
    noctowl: "brown",
    sudowoodo: "brown",
    ursaring: "brown",
    piloswine: "brown",
    stantler: "brown",
    entei: "brown",
    zigzagoon: "brown",
    seedot: "brown",
    shroomish: "brown",
    slakoth: "brown",
    hitmontop: "brown",
    nuzleaf: "brown",
    shiftry: "brown",
    slaking: "brown",
    shedinja: "brown",
    hariyama: "brown",
    torkoal: "brown",
    spinda: "brown",
    trapinch: "brown",
    baltoy: "brown",
    feebas: "brown",
    regirock: "brown",
    chimchar: "brown",
    starly: "brown",
    bidoof: "brown",
    buizel: "brown",
    buneary: "brown",
    bonsly: "brown",
    hippopotas: "brown",
    infernape: "brown",
    staravia: "brown",
    staraptor: "brown",
    bibarel: "brown",
    floatzel: "brown",
    lopunny: "brown",
    hippowdon: "brown",
    heatran: "brown",
    patrat: "brown",
    lillipup: "brown",
    watchog: "brown",
    sandile: "brown",
    conkeldurr: "brown",
    krokorok: "brown",
    sawsbuck: "brown",
    beheeyem: "brown",
    stunfisk: "brown",
    bouffalant: "brown",
    vullaby: "brown",
    landorus: "brown",
    bunnelby: "brown",
    litleo: "brown",
    skiddo: "brown",
    honedge: "brown",
    mandibuzz: "brown",
    diggersby: "brown",
    pyroar: "brown",
    gogoat: "brown",
    doublade: "brown",
    aegislash: "brown",
    binacle: "brown",
    skrelp: "brown",
    tyrunt: "brown",
    phantump: "brown",
    pumpkaboo: "brown",
    volcanion: "brown",
    rowlet: "brown",
    yungoos: "brown",
    rockruff: "brown",
    mudbray: "brown",
    barbaracle: "brown",
    dragalge: "brown",
    trevenant: "brown",
    gourgeist: "brown",
    dartrix: "brown",
    decidueye: "brown",
    gumshoos: "brown",
    lycanroc: "brown",
    mudsdale: "brown",
    sandygast: "brown",
    minior: "brown",
    skwovet: "brown",
    nickit: "brown",
    palossand: "brown",
    greedent: "brown",
    thievul: "brown",
    arrokuda: "brown",
    clobbopus: "brown",
    golem: "brown",
    monferno: "brown",
    mamoswine: "brown",
    barraskewda: "brown",
    perrserker: "brown",

    // yellow
    sandshrew: "yellow",
    meowth: "yellow",
    psyduck: "yellow",
    kakuna: "yellow",
    beedrill: "yellow",
    pikachu: "yellow",
    raichu: "yellow",
    sandslash: "yellow",
    ninetales: "yellow",
    persian: "yellow",
    ponyta: "yellow",
    drowzee: "yellow",
    zapdos: "yellow",
    moltres: "yellow",
    rapidash: "yellow",
    hypno: "yellow",
    exeggutor: "yellow",
    electabuzz: "yellow",
    jolteon: "yellow",
    cyndaquil: "yellow",
    pichu: "yellow",
    sunkern: "yellow",
    girafarig: "yellow",
    dunsparce: "yellow",
    shuckle: "yellow",
    quilava: "yellow",
    typhlosion: "yellow",
    ampharos: "yellow",
    sunflora: "yellow",
    elekid: "yellow",
    raikou: "yellow",
    makuhita: "yellow",
    beautifly: "yellow",
    pelipper: "yellow",
    ninjask: "yellow",
    plusle: "yellow",
    minun: "yellow",
    numel: "yellow",
    lunatone: "yellow",
    manectric: "yellow",
    jirachi: "yellow",
    combee: "yellow",
    chingling: "yellow",
    mothim: "yellow",
    vespiquen: "yellow",
    uxie: "yellow",
    cresselia: "yellow",
    victini: "yellow",
    electivire: "yellow",
    sewaddle: "yellow",
    scraggy: "yellow",
    archen: "yellow",
    joltik: "yellow",
    leavanny: "yellow",
    archeops: "yellow",
    galvantula: "yellow",
    mienfoo: "yellow",
    keldeo: "yellow",
    haxorus: "yellow",
    helioptile: "yellow",
    dedenne: "yellow",
    cutiefly: "yellow",
    heliolisk: "yellow",
    ribombee: "yellow",
    mimikyu: "yellow",
    "tapu-koko": "yellow",
    zeraora: "yellow",
    yamper: "yellow",
    dottler: "yellow",
    boltund: "yellow",
    falinks: "yellow",
    morpeko: "yellow",
    cufant: "yellow",
    regieleki: "yellow",
    cofagrigus: "yellow",

    // white
    butterfree: "white",
    seel: "white",
    dewgong: "white",
    togepi: "white",
    mareep: "white",
    togetic: "white",
    smeargle: "white",
    lugia: "white",
    wingull: "white",
    ralts: "white",
    linoone: "white",
    silcoon: "white",
    kirlia: "white",
    gardevoir: "white",
    vigoroth: "white",
    zangoose: "white",
    absol: "white",
    shelgon: "white",
    pachirisu: "white",
    snover: "white",
    dialga: "white",
    regigigas: "white",
    arceus: "white",
    abomasnow: "white",
    togekiss: "white",
    gallade: "white",
    froslass: "white",
    vanillite: "white",
    emolga: "white",
    foongus: "white",
    frillish: "white",
    tynamo: "white",
    litwick: "white",
    swanna: "white",
    vanillish: "white",
    vanilluxe: "white",
    amoonguss: "white",
    jellicent: "white",
    cubchoo: "white",
    rufflet: "white",
    larvesta: "white",
    reshiram: "white",
    meloetta: "white",
    flabebe: "white",
    pancham: "white",
    furfrou: "white",
    swirlix: "white",
    beartic: "white",
    volcarona: "white",
    floette: "white",
    florges: "white",
    pangoro: "white",
    slurpuff: "white",
    crabominable: "white",
    oranguru: "white",
    passimian: "white",
    drampa: "white",
    nihilego: "white",
    pheromosa: "white",
    kartana: "white",
    blacephalon: "white",
    scorbunny: "white",
    wooloo: "white",
    solgaleo: "white",
    cinderace: "white",
    dubwool: "white",
    milcery: "white",
    snom: "white",
    duraludon: "white",
    glastrier: "white",
    vivillon: "white",
    cursola: "white",
    sirfetchd: "white",
    alcremie: "white",
    frosmoth: "white",

    // red
    charmander: "red",
    paras: "red",
    charmeleon: "red",
    charizard: "red",
    vileplume: "red",
    parasect: "red",
    krabby: "red",
    voltorb: "red",
    goldeen: "red",
    magikarp: "red",
    kingler: "red",
    electrode: "red",
    seaking: "red",
    jynx: "red",
    magmar: "red",
    flareon: "red",
    ledyba: "red",
    yanma: "red",
    slugma: "red",
    delibird: "red",
    ledian: "red",
    ariados: "red",
    scizor: "red",
    magcargo: "red",
    octillery: "red",
    magby: "red",
    "ho-oh": "red",
    torchic: "red",
    wurmple: "red",
    "porygon2": "red",
    combusken: "red",
    blaziken: "red",
    carvanha: "red",
    solrock: "red",
    corphish: "red",
    medicham: "red",
    camerupt: "red",
    crawdaunt: "red",
    latias: "red",
    groudon: "red",
    deoxys: "red",
    kricketot: "red",
    kricketune: "red",
    rotom: "red",
    tepig: "red",
    pansear: "red",
    magmortar: "red",
    "porygon-z": "red",
    pignite: "red",
    emboar: "red",
    simisear: "red",
    throh: "red",
    venipede: "red",
    darumaka: "red",
    dwebble: "red",
    scolipede: "red",
    krookodile: "red",
    darmanitan: "red",
    crustle: "red",
    scrafty: "red",
    shelmet: "red",
    druddigon: "red",
    pawniard: "red",
    heatmor: "red",
    fennekin: "red",
    fletchling: "red",
    accelgor: "red",
    bisharp: "red",
    braviary: "red",
    braixen: "red",
    delphox: "red",
    fletchinder: "red",
    talonflame: "red",
    yveltal: "red",
    litten: "red",
    oricorio: "red",
    torracat: "red",
    incineroar: "red",
    turtonator: "red",
    "tapu-bulu": "red",
    buzzwole: "red",
    orbeetle: "red",
    sizzlipede: "red",
    zamazenta: "red",
    tyrantrum: "red",
    centiskorch: "red",

    // pink
    rattata: "purple",
    ekans: "purple",
    "nidoran-m": "purple",
    zubat: "purple",
    venonat: "purple",
    arbok: "purple",
    nidorino: "purple",
    nidoking: "purple",
    golbat: "purple",
    venomoth: "purple",
    grimer: "purple",
    shellder: "purple",
    gastly: "purple",
    koffing: "purple",
    ditto: "purple",
    aerodactyl: "purple",
    mewtwo: "purple",
    muk: "purple",
    cloyster: "purple",
    haunter: "purple",
    gengar: "purple",
    weezing: "purple",
    starmie: "purple",
    aipom: "purple",
    gligar: "purple",
    crobat: "purple",
    espeon: "purple",
    forretress: "purple",
    granbull: "purple",
    tyrogue: "purple",
    cascoon: "purple",
    sableye: "purple",
    illumise: "purple",
    lileep: "purple",
    swalot: "purple",
    grumpig: "purple",
    shellos: "purple",
    drifloon: "purple",
    stunky: "purple",
    spiritomb: "purple",
    skorupi: "purple",
    cherrim: "purple",
    ambipom: "purple",
    drifblim: "purple",
    mismagius: "purple",
    skuntank: "purple",
    drapion: "purple",
    palkia: "purple",
    purrloin: "purple",
    gliscor: "purple",
    liepard: "purple",
    gothita: "purple",
    gothorita: "purple",
    gothitelle: "purple",
    genesect: "purple",
    goomy: "purple",
    noibat: "purple",
    hoopa: "purple",
    crabrawler: "purple",
    morelull: "purple",
    bounsweet: "purple",
    sliggoo: "purple",
    goodra: "purple",
    noivern: "purple",
    shiinotic: "purple",
    steenee: "purple",
    "tapu-fini": "purple",
    poipole: "purple",
    lunala: "purple",
    naganadel: "purple",
    toxel: "purple",
    sinistea: "purple",
    pincurchin: "purple",
    indeedee: "purple",
    eternatus: "purple",
    mantine: "purple",
    delcatty: "purple",
    gastrodon: "purple",
    mienshao: "purple",
    toxtricity: "purple",
    polteageist: "purple",
    grimmsnarl: "purple",
    "mr-rime": "purple",
    tsareena: "purple",
    corviknight: "purple",

    // pink
    clefairy: "pink",
    clefable: "pink",
    jigglypuff: "pink",
    wigglytuff: "pink",
    slowpoke: "pink",
    exeggcute: "pink",
    lickitung: "pink",
    porygon: "pink",
    slowbro: "pink",
    chansey: "pink",
    "mr-mime": "pink",
    mew: "pink",
    cleffa: "pink",
    igglybuff: "pink",
    hoppip: "pink",
    snubbull: "pink",
    corsola: "pink",
    flaaffy: "pink",
    slowking: "pink",
    smoochum: "pink",
    miltank: "pink",
    whismur: "pink",
    skitty: "pink",
    blissey: "pink",
    luvdisc: "pink",
    milotic: "pink",
    gorebyss: "pink",
    cherubi: "pink",
    "mime-jr": "pink",
    happiny: "pink",
    mesprit: "pink",
    munna: "pink",
    audino: "pink",
    lickilicky: "pink",
    musharna: "pink",
    deerling: "pink",
    alomomola: "pink",
    spritzee: "pink",
    aromatisse: "pink",
    diancie: "pink",
    fomantis: "pink",
    stufful: "pink",
    sylveon: "pink",
    lurantis: "pink",
    bewear: "pink",
    bruxish: "pink",
    "tapu-lele": "pink",
    hatenna: "pink",
    impidimp: "pink",
    hattrem: "pink",
    morgrem: "pink",
    hatterene: "pink",

    // green
    bulbasaur: "green",
    caterpie: "green",
    bellsprout: "green",
    venusaur: "green",
    metapod: "green",
    weepinbell: "green",
    victreebel: "green",
    scyther: "green",
    chikorita: "green",
    spinarak: "green",
    natu: "green",
    meganium: "green",
    xatu: "green",
    bellossom: "green",
    politoed: "green",
    skiploom: "green",
    larvitar: "green",
    celebi: "green",
    treecko: "green",
    lotad: "green",
    tyranitar: "green",
    grovyle: "green",
    sceptile: "green",
    dustox: "green",
    lombre: "green",
    ludicolo: "green",
    breloom: "green",
    electrike: "green",
    gulpin: "green",
    cacnea: "green",
    kecleon: "green",
    tropius: "green",
    roselia: "green",
    vibrava: "green",
    flygon: "green",
    cacturne: "green",
    cradily: "green",
    rayquaza: "green",
    turtwig: "green",
    budew: "green",
    burmy: "green",
    bronzor: "green",
    grotle: "green",
    torterra: "green",
    roserade: "green",
    wormadam: "green",
    bronzong: "green",
    carnivine: "green",
    shaymin: "green",
    snivy: "green",
    pansage: "green",
    yanmega: "green",
    leafeon: "green",
    servine: "green",
    serperior: "green",
    simisage: "green",
    cottonee: "green",
    petilil: "green",
    basculin: "green",
    maractus: "green",
    trubbish: "green",
    solosis: "green",
    swadloon: "green",
    whimsicott: "green",
    lilligant: "green",
    garbodor: "green",
    duosion: "green",
    reuniclus: "green",
    axew: "green",
    golett: "green",
    virizion: "green",
    tornadus: "green",
    chespin: "green",
    fraxure: "green",
    golurk: "green",
    quilladin: "green",
    chesnaught: "green",
    hawlucha: "green",
    zygarde: "green",
    dewpider: "green",
    comfey: "green",
    charjabug: "green",
    araquanid: "green",
    dhelmise: "green",
    celesteela: "green",
    grookey: "green",
    gossifleur: "green",
    chewtle: "green",
    applin: "green",
    thwackey: "green",
    rillaboom: "green",
    eldegoss: "green",
    drednaw: "green",
    flapple: "green",
    silicobra: "green",
    dracozolt: "green",
    dracovish: "green",
    dreepy: "green",
    zarude: "green",
    regidrago: "green",
    calyrex: "green",
    ivysaur: "green",
    bayleef: "green",
    sandaconda: "green",
    copperajah: "green",
    drakloak: "green",
    dragapult: "green",
    appletun: "green",

    // gray
    machop: "gray",
    machoke: "gray",
    machamp: "gray",
    magnemite: "gray",
    onix: "gray",
    rhyhorn: "gray",
    magneton: "gray",
    rhydon: "gray",
    misdreavus: "gray",
    pineco: "gray",
    qwilfish: "gray",
    remoraid: "gray",
    steelix: "gray",
    skarmory: "gray",
    poochyena: "gray",
    nincada: "gray",
    nosepass: "gray",
    donphan: "gray",
    pupitar: "gray",
    mightyena: "gray",
    aron: "gray",
    volbeat: "gray",
    barboach: "gray",
    anorith: "gray",
    castform: "gray",
    snorunt: "gray",
    relicanth: "gray",
    lairon: "gray",
    aggron: "gray",
    armaldo: "gray",
    glalie: "gray",
    registeel: "gray",
    shieldon: "gray",
    glameow: "gray",
    bastiodon: "gray",
    purugly: "gray",
    pidove: "gray",
    drilbur: "gray",
    magnezone: "gray",
    rhyperior: "gray",
    probopass: "gray",
    stoutland: "gray",
    tranquill: "gray",
    unfezant: "gray",
    excadrill: "gray",
    timburr: "gray",
    zorua: "gray",
    minccino: "gray",
    ferroseed: "gray",
    klink: "gray",
    whirlipede: "gray",
    zoroark: "gray",
    cinccino: "gray",
    escavalier: "gray",
    ferrothorn: "gray",
    klang: "gray",
    durant: "gray",
    terrakion: "gray",
    kyurem: "gray",
    espurr: "gray",
    carbink: "gray",
    klefki: "gray",
    grubbin: "gray",
    wimpod: "gray",
    "type-null": "gray",
    togedemaru: "gray",
    "jangmo-o": "gray",
    magearna: "gray",
    marshadow: "gray",
    stakataka: "gray",
    meltan: "gray",
    silvally: "gray",
    "hakamo-o": "gray",
    "kommo-o": "gray",
    melmetal: "gray",
    raboot: "gray",
    stonjourner: "gray",
    kubfu: "gray",
    herdier: "gray",
    gurdurr: "gray",
    klinklang: "gray",
    obstagoon: "gray",
    runerigus: "gray",
    urshifu: "gray",
    golisopod: "gray",
};

export const determineStatColor = (statName: string) => {
    switch (statName) {
        case "hp":
            return "#fb6c6c";
        case "attack":
            return "#ff7f11";
        case "defense":
            return "#ffce4b";
        case "special-attack":
            return "#59acf4";
        case "special-defense":
            return "#49d0b0";
        case "speed":
            return "#ff758f";
        default:
            return "#606160";
    }
};

export const pokemons = [
    { "name": "Bulbasaur", "id": "1" },
    { "name": "Ivysaur", "id": "2" },
    { "name": "Venusaur", "id": "3" },
    { "name": "Charmander", "id": "4" },
    { "name": "Charmeleon", "id": "5" },
    { "name": "Charizard", "id": "6" },
    { "name": "Squirtle", "id": "7" },
    { "name": "Wartortle", "id": "8" },
    { "name": "Blastoise", "id": "9" },
    { "name": "Caterpie", "id": "10" },
    { "name": "Metapod", "id": "11" },
    { "name": "Butterfree", "id": "12" },
    { "name": "Weedle", "id": "13" },
    { "name": "Kakuna", "id": "14" },
    { "name": "Beedrill", "id": "15" },
    { "name": "Pidgey", "id": "16" },
    { "name": "Pidgeotto", "id": "17" },
    { "name": "Pidgeot", "id": "18" },
    { "name": "Rattata", "id": "19" },
    { "name": "Raticate", "id": "20" },
    { "name": "Spearow", "id": "21" },
    { "name": "Fearow", "id": "22" },
    { "name": "Ekans", "id": "23" },
    { "name": "Arbok", "id": "24" },
    { "name": "Pikachu", "id": "25" },
    { "name": "Raichu", "id": "26" },
    { "name": "Sandshrew", "id": "27" },
    { "name": "Sandslash", "id": "28" },
    { "name": "Nidoran-f", "id": "29" },
    { "name": "Nidorina", "id": "30" },
    { "name": "Nidoqueen", "id": "31" },
    { "name": "Nidoran-m", "id": "32" },
    { "name": "Nidorino", "id": "33" },
    { "name": "Nidoking", "id": "34" },
    { "name": "Clefairy", "id": "35" },
    { "name": "Clefable", "id": "36" },
    { "name": "Vulpix", "id": "37" },
    { "name": "Ninetales", "id": "38" },
    { "name": "Jigglypuff", "id": "39" },
    { "name": "Wigglytuff", "id": "40" },
    { "name": "Zubat", "id": "41" },
    { "name": "Golbat", "id": "42" },
    { "name": "Oddish", "id": "43" },
    { "name": "Gloom", "id": "44" },
    { "name": "Vileplume", "id": "45" },
    { "name": "Paras", "id": "46" },
    { "name": "Parasect", "id": "47" },
    { "name": "Venonat", "id": "48" },
    { "name": "Venomoth", "id": "49" },
    { "name": "Diglett", "id": "50" },
    { "name": "Dugtrio", "id": "51" },
    { "name": "Meowth", "id": "52" },
    { "name": "Persian", "id": "53" },
    { "name": "Psyduck", "id": "54" },
    { "name": "Golduck", "id": "55" },
    { "name": "Mankey", "id": "56" },
    { "name": "Primeape", "id": "57" },
    { "name": "Growlithe", "id": "58" },
    { "name": "Arcanine", "id": "59" },
    { "name": "Poliwag", "id": "60" },
    { "name": "Poliwhirl", "id": "61" },
    { "name": "Poliwrath", "id": "62" },
    { "name": "Abra", "id": "63" },
    { "name": "Kadabra", "id": "64" },
    { "name": "Alakazam", "id": "65" },
    { "name": "Machop", "id": "66" },
    { "name": "Machoke", "id": "67" },
    { "name": "Machamp", "id": "68" },
    { "name": "Bellsprout", "id": "69" },
    { "name": "Weepinbell", "id": "70" },
    { "name": "Victreebel", "id": "71" },
    { "name": "Tentacool", "id": "72" },
    { "name": "Tentacruel", "id": "73" },
    { "name": "Geodude", "id": "74" },
    { "name": "Graveler", "id": "75" },
    { "name": "Golem", "id": "76" },
    { "name": "Ponyta", "id": "77" },
    { "name": "Rapidash", "id": "78" },
    { "name": "Slowpoke", "id": "79" },
    { "name": "Slowbro", "id": "80" },
    { "name": "Magnemite", "id": "81" },
    { "name": "Magneton", "id": "82" },
    { "name": "Farfetchd", "id": "83" },
    { "name": "Doduo", "id": "84" },
    { "name": "Dodrio", "id": "85" },
    { "name": "Seel", "id": "86" },
    { "name": "Dewgong", "id": "87" },
    { "name": "Grimer", "id": "88" },
    { "name": "Muk", "id": "89" },
    { "name": "Shellder", "id": "90" },
    { "name": "Cloyster", "id": "91" },
    { "name": "Gastly", "id": "92" },
    { "name": "Haunter", "id": "93" },
    { "name": "Gengar", "id": "94" },
    { "name": "Onix", "id": "95" },
    { "name": "Drowzee", "id": "96" },
    { "name": "Hypno", "id": "97" },
    { "name": "Krabby", "id": "98" },
    { "name": "Kingler", "id": "99" },
    { "name": "Voltorb", "id": "100" },
    { "name": "Electrode", "id": "101" },
    { "name": "Exeggcute", "id": "102" },
    { "name": "Exeggutor", "id": "103" },
    { "name": "Cubone", "id": "104" },
    { "name": "Marowak", "id": "105" },
    { "name": "Hitmonlee", "id": "106" },
    { "name": "Hitmonchan", "id": "107" },
    { "name": "Lickitung", "id": "108" },
    { "name": "Koffing", "id": "109" },
    { "name": "Weezing", "id": "110" },
    { "name": "Rhyhorn", "id": "111" },
    { "name": "Rhydon", "id": "112" },
    { "name": "Chansey", "id": "113" },
    { "name": "Tangela", "id": "114" },
    { "name": "Kangaskhan", "id": "115" },
    { "name": "Horsea", "id": "116" },
    { "name": "Seadra", "id": "117" },
    { "name": "Goldeen", "id": "118" },
    { "name": "Seaking", "id": "119" },
    { "name": "Staryu", "id": "120" },
    { "name": "Starmie", "id": "121" },
    { "name": "Mr-mime", "id": "122" },
    { "name": "Scyther", "id": "123" },
    { "name": "Jynx", "id": "124" },
    { "name": "Electabuzz", "id": "125" },
    { "name": "Magmar", "id": "126" },
    { "name": "Pinsir", "id": "127" },
    { "name": "Tauros", "id": "128" },
    { "name": "Magikarp", "id": "129" },
    { "name": "Gyarados", "id": "130" },
    { "name": "Lapras", "id": "131" },
    { "name": "Ditto", "id": "132" },
    { "name": "Eevee", "id": "133" },
    { "name": "Vaporeon", "id": "134" },
    { "name": "Jolteon", "id": "135" },
    { "name": "Flareon", "id": "136" },
    { "name": "Porygon", "id": "137" },
    { "name": "Omanyte", "id": "138" },
    { "name": "Omastar", "id": "139" },
    { "name": "Kabuto", "id": "140" },
    { "name": "Kabutops", "id": "141" },
    { "name": "Aerodactyl", "id": "142" },
    { "name": "Snorlax", "id": "143" },
    { "name": "Articuno", "id": "144" },
    { "name": "Zapdos", "id": "145" },
    { "name": "Moltres", "id": "146" },
    { "name": "Dratini", "id": "147" },
    { "name": "Dragonair", "id": "148" },
    { "name": "Dragonite", "id": "149" },
    { "name": "Mewtwo", "id": "150" },
    { "name": "Mew", "id": "151" },
    { "name": "Chikorita", "id": "152" },
    { "name": "Bayleef", "id": "153" },
    { "name": "Meganium", "id": "154" },
    { "name": "Cyndaquil", "id": "155" },
    { "name": "Quilava", "id": "156" },
    { "name": "Typhlosion", "id": "157" },
    { "name": "Totodile", "id": "158" },
    { "name": "Croconaw", "id": "159" },
    { "name": "Feraligatr", "id": "160" },
    { "name": "Sentret", "id": "161" },
    { "name": "Furret", "id": "162" },
    { "name": "Hoothoot", "id": "163" },
    { "name": "Noctowl", "id": "164" },
    { "name": "Ledyba", "id": "165" },
    { "name": "Ledian", "id": "166" },
    { "name": "Spinarak", "id": "167" },
    { "name": "Ariados", "id": "168" },
    { "name": "Crobat", "id": "169" },
    { "name": "Chinchou", "id": "170" },
    { "name": "Lanturn", "id": "171" },
    { "name": "Pichu", "id": "172" },
    { "name": "Cleffa", "id": "173" },
    { "name": "Igglybuff", "id": "174" },
    { "name": "Togepi", "id": "175" },
    { "name": "Togetic", "id": "176" },
    { "name": "Natu", "id": "177" },
    { "name": "Xatu", "id": "178" },
    { "name": "Mareep", "id": "179" },
    { "name": "Flaaffy", "id": "180" },
    { "name": "Ampharos", "id": "181" },
    { "name": "Bellossom", "id": "182" },
    { "name": "Marill", "id": "183" },
    { "name": "Azumarill", "id": "184" },
    { "name": "Sudowoodo", "id": "185" },
    { "name": "Politoed", "id": "186" },
    { "name": "Hoppip", "id": "187" },
    { "name": "Skiploom", "id": "188" },
    { "name": "Jumpluff", "id": "189" },
    { "name": "Aipom", "id": "190" },
    { "name": "Sunkern", "id": "191" },
    { "name": "Sunflora", "id": "192" },
    { "name": "Yanma", "id": "193" },
    { "name": "Wooper", "id": "194" },
    { "name": "Quagsire", "id": "195" },
    { "name": "Espeon", "id": "196" },
    { "name": "Umbreon", "id": "197" },
    { "name": "Murkrow", "id": "198" },
    { "name": "Slowking", "id": "199" },
    { "name": "Misdreavus", "id": "200" },
    { "name": "Unown", "id": "201" },
    { "name": "Wobbuffet", "id": "202" },
    { "name": "Girafarig", "id": "203" },
    { "name": "Pineco", "id": "204" },
    { "name": "Forretress", "id": "205" },
    { "name": "Dunsparce", "id": "206" },
    { "name": "Gligar", "id": "207" },
    { "name": "Steelix", "id": "208" },
    { "name": "Snubbull", "id": "209" },
    { "name": "Granbull", "id": "210" },
    { "name": "Qwilfish", "id": "211" },
    { "name": "Scizor", "id": "212" },
    { "name": "Shuckle", "id": "213" },
    { "name": "Heracross", "id": "214" },
    { "name": "Sneasel", "id": "215" },
    { "name": "Teddiursa", "id": "216" },
    { "name": "Ursaring", "id": "217" },
    { "name": "Slugma", "id": "218" },
    { "name": "Magcargo", "id": "219" },
    { "name": "Swinub", "id": "220" },
    { "name": "Piloswine", "id": "221" },
    { "name": "Corsola", "id": "222" },
    { "name": "Remoraid", "id": "223" },
    { "name": "Octillery", "id": "224" },
    { "name": "Delibird", "id": "225" },
    { "name": "Mantine", "id": "226" },
    { "name": "Skarmory", "id": "227" },
    { "name": "Houndour", "id": "228" },
    { "name": "Houndoom", "id": "229" },
    { "name": "Kingdra", "id": "230" },
    { "name": "Phanpy", "id": "231" },
    { "name": "Donphan", "id": "232" },
    { "name": "Porygon2", "id": "233" },
    { "name": "Stantler", "id": "234" },
    { "name": "Smeargle", "id": "235" },
    { "name": "Tyrogue", "id": "236" },
    { "name": "Hitmontop", "id": "237" },
    { "name": "Smoochum", "id": "238" },
    { "name": "Elekid", "id": "239" },
    { "name": "Magby", "id": "240" },
    { "name": "Miltank", "id": "241" },
    { "name": "Blissey", "id": "242" },
    { "name": "Raikou", "id": "243" },
    { "name": "Entei", "id": "244" },
    { "name": "Suicune", "id": "245" },
    { "name": "Larvitar", "id": "246" },
    { "name": "Pupitar", "id": "247" },
    { "name": "Tyranitar", "id": "248" },
    { "name": "Lugia", "id": "249" },
    { "name": "Ho-oh", "id": "250" },
    { "name": "Celebi", "id": "251" }
]

export function determinePokemonColor(color: string) {
    switch (color) {
        case "red":
            return {
                background: "#fb6c6c",
                badge: "#fc9c9c",
                badgeTextColor: "#FFFFFF",
            };
        case "blue":
            return {
                background: "#59acf4",
                badge: "#87bbe8",
                badgeTextColor: "#FFFFFF",
            };
        case "purple":
            return {
                background: "#7b548b",
                badge: "#9b73ab",
                badgeTextColor: "#FFFFFF",
            };
        case "yellow":
            return {
                background: "#ffce4b",
                badge: "#ffde85",
                badgeTextColor: "#FFFFFF",
            };
        case "green":
            return {
                background: "#49d0b0",
                badge: "#7ddec7",
                badgeTextColor: "#FFFFFF",
            };
        case "brown":
            return {
                background: "#b1736c",
                badge: "#c08c87",
                badgeTextColor: "#FFFFFF",
            };
        case "white":
            return {
                background: "#f4f5f4",
                badge: "#dfe2df",
                badgeTextColor: "#000000",
            };
        case "pink":
            return {
                background: "#f89997",
                badge: "#f5b9b5",
                badgeTextColor: "#FFFFFF",
            };
        case "gray":
            return {
                background: "#949a94",
                badge: "#c2cac2",
                badgeTextColor: "#000000",
            };
        default:
            return {
                background: "#383a38",
                badge: "#505350",
                badgeTextColor: "#FFFFFF",
            };
    }
}
